version: '2'
services:
  mongo:
    image: mongo
    container_name: mongo
    env:
      MONGO_URL: "mongo"
      MONGO_DATABASE: "magicbox"
    ports:
      - "27017:27017"
  magicbox:
    build: .
    container_name: jenarvaezg/magicbox
    ports:
      - "8000:8000"
    links:
        - mongo
