version: '2'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  magicbox:
    build: .
    container_name: magicbox
    ports:
      - "8000:8000"
    links:
        - mongo
