version: '2'
services:
  mongo:
    image: mongo:3.4
    container_name: mongo
    hostname: mongo
    volumes:
      - ./data:/data/db
  magicbox:
    image: jenarvaezg/magicbox:0.2.2
    container_name: magicbox
    environment:
      - MONGO_URL=mongo
      - MONGO_DATABASE=magicbox
    ports:
      - 8000:8000
    links:
      - mongo
