version: '2'
services:
  mongo:
    image: mongo:3.4
    container_name: mongo
    hostname: mongo
    volumes:
      - ./data:/data/db
<<<<<<< HEAD
  magichub:
    image: jenarvaezg/magichub:0.2.4
    container_name: magichub
=======
  magicbox:
    image: jenarvaezg/magicbox:0.2.4
    container_name: magicbox
>>>>>>> master
    environment:
      - MONGO_URL=mongo
      - MONGO_DATABASE=magichub
    ports:
      - 8000:8000
    links:
      - mongo
